name: Terraform Destroy CI/CD Workflow

on:
  workflow_dispatch:  # Manualny wyzwalacz uruchamiany z UI GitHub
    inputs:
      confirmation:
        description: 'Type "destroy" to confirm destruction of infrastructure'
        required: true
        default: 'destroy'  # Możesz ustawić domyślną wartość jako "destroy", aby użytkownik musiał ją zatwierdzić

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Krok 2: Logowanie do Azure CLI z użyciem device code (interaktywne)
      - name: Log in to Azure CLI
        run: |
          az login --use-device-code

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Destroy
        run: terraform destroy -auto-approve
        continue-on-error: true  # Pozwól kontynuować, nawet jeśli błąd wystąpi

      - name: Retry if Terraform Destroy failed
        if: failure()  # Wykonaj tylko w przypadku błędu
        run: terraform destroy -auto-approve

      - name: Retry if Terraform Destroy failed 2
        if: failure()  # Wykonaj tylko w przypadku błędu
        run: terraform destroy -auto-approve